swagger: "2.0"
tags:
  - Motor
consumes:
- application/json
- application/xml
produces:
- application/xml
- application/json
parameters:
  - in: path
    name: id
    required: true
    description: The ID of the motor,try 1~3
    type: string
  - in: query
    name: info
    required: false
    description: return info or not
    type: boolean
responses:
  200:
    description: A brief description of the interested motor