swagger: "2.0"
tags:
  - Motor
consumes:
- application/json
- application/xml
produces:
- application/xml
- application/json
parameters:
  - in: query
    name: filter_by
    required: false
    description: field used for filter motor
    type: string
    enum:
    - statu
    default: statu
responses:
  200:
    description: Statistic of the motors.