swagger: "2.0"
tags:
  - Motor
parameters:
  - in: path
    name: id
    required: true
    description: The ID of the related motor,try 1~3
    type: string
responses:
  200:
    description: Rotor collections of the motor.