swagger: "2.0"
tags:
  - Motor
consumes:
- application/json
- application/xml
produces:
- application/xml
- application/json
parameters:
  - in: path
    name: id
    required: true
    description: The ID of the motor,try 1~3
    type: string
  - in: query
    name: lr_time
    required: true
    description: Last repair time, pattern like:2019-03-22 16:37:08
    type: string
responses:
  200:
    description: Update last repair time of the motor