swagger: "2.0"
tags:
  - Motor
consumes:
- application/json
- application/xml
produces:
- application/xml
- application/json
parameters:
  - in: path
    name: id
    required: true
    description: The ID of the related motor,try 1~3
    type: int
    default: 2
  - in: query
    name: feature
    required: true
    description: chose one or more of [rms, max_current, min_current, thd, imbalance,harmonics,fbrb,n_rms,p_rms,z_rms]
    type: array
    enum:
     - rms
     'max_current', 'min_current', 'thd', 'imbalance','n_rms','p_rms','z_rms']

  - in: query
    name: timeafter
    required: true
    description: Start time, pattern:2016-01-01 00:00:00
    type: string
    formatter: date-time
    default: 2016-01-01 00:00:00
  - in: query
    name: timebefore
    required: true
    description: End time, pattern:2016-05-01 00:00:00
    type: string
    formatter: date-time