swagger: "2.0"
tags:
  - Warning
consumes:
- application/json
- application/xml
produces:
- application/xml
- application/json
parameters:
  - in: query
    name: limit
    required: false
    type: integer
  - in: query
    name: group_by
    required: false
    type: string
    enum:
     - motor
     - date
responses:
  200:
    description: Success