swagger: "2.0"
tags:
  - Motor Feature
consumes:
  - application/json
  - application/xml
produces:
  - application/xml
  - application/json
parameters:
  - in: path
    name: id
    required: true
    description: The ID of the related motor,try 1~3
    type: integer
    default: 2
  - in: query
    name: feature
    required: false
    description: chose one or more of [rms, max_current, min_current, thd, imbalance,harmonics,fbrb,n_rms,p_rms,z_rms]
    type: array
    items:
      type: string
      enum:
        - urms
        - uthd
        - umax_current
        - umin_current
        - ufrequency
        - uamplitude
        - uinitial_phase
        - vrms
        - vthd
        - vmax_current
        - vmin_current
        - vfrequency
        - vamplitude
        - vinitial_phase
        - wrms
        - wthd
        - wmax_current
        - wmin_current
        - wfrequency
        - wamplitude
        - winitial_phase
        - imbalance
        - n_rms
        - p_rms
        - z_rms
  - in: query
    name: timeafter
    required: false
    description: 起始时间，模式为：2016-01-01 00:00:00
    type: string
  - in: query
    name: timebefore
    required: false
    description: 截止时间，模式为：2016-05-01 00:00:00
    type: string
  - in: query
    name: newest
    required: false
    type: boolean
responses:
  200:
    description: Success
  400:
    description: Bad query