swagger: "2.0"
tags:
  - Equip Group
consumes:
- application/json
- application/xml
produces:
- application/xml
- application/json
parameters:
  - in: query
    name: iftree
    description: Determine whether to return the tree map of equipment structure.
    type: boolean
    default: false
responses:
  200:
    description: A brief description of the interested equip group