swagger: "2.0"
tags:
  - Motor
parameters:
  - in: path
    name: id
    required: true
    description: The ID of the related motor,try 1~3. or id of the asset, depending on the url.
    type: string
  - in: query
    name: info
    required: false
    description: return info or not
    type: boolean
responses:
  200:
    description: Bearing collection of the motor.